apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-echo
spec:
  ingressClassName: nginx
  rules:
  - host: echo.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-echo
            port:
              number: 80
